# Generated by Django 6.0.4 on 2026-04-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=150)),
                ('cargo', models.CharField(blank=True, max_length=150, null=True)),
                ('empresa', models.CharField(blank=True, max_length=150, null=True)),
                ('contenido', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='proyectos/')),
                ('puntuacion', models.PositiveSmallIntegerField(default=5)),
                ('destacado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['orden', '-creado'],
            },
        ),
    ]

