# Generated by Django 6.0.4 on 2026-04-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_proyecto_slug_imagenproyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
