# Generated by Django 6.0.1 on 2026-04-17 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajecontacto',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
