# Generated by Django 6.0.4 on 2026-04-15 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=150)),
                ('slogan', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresa/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='empresa/')),
                ('color_primario', models.CharField(default='#0f172a', max_length=20)),
                ('color_secundario', models.CharField(default='#2563eb', max_length=20)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('titulo_hero', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitulo_hero', models.CharField(blank=True, max_length=255, null=True)),
                ('imagen_hero', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Perfil de empresa',
                'verbose_name_plural': 'Perfil de empresa',
            },
        ),
    ]
