# Generated by Django 6.0.4 on 2026-04-16 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilempresa',
            name='rubro',
            field=models.CharField(blank=True, help_text='Rubro de la empresa', max_length=120, null=True),
        ),
    ]
