# Generated by Django 6.0.4 on 2026-04-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_perfilempresa_rubro'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilempresa',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
