# Generated by Django 6.0.4 on 2026-04-17 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_perfilempresa_ubicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilempresa',
            name='ubicacion',
        ),
    ]
