# Generated by Django 6.0.4 on 2026-04-18 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_perfilempresa_ubicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilempresa',
            name='favicon',
        ),
    ]
