# Generated by Django 6.0.4 on 2026-04-18 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_perfilempresa_favicon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilempresa',
            name='favicon',
        ),
    ]
