# Generated by Django 6.0.4 on 2026-04-18 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_perfilempresa_favicon'),
        ('core', '0006_restore_perfilempresa_favicon'),
    ]

    operations = [
    ]
