# Generated by Django 6.0.4 on 2026-04-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20260417_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilempresa',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='empresa/'),
        ),
    ]
