# Generated by Django 6.0.4 on 2026-04-15 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('descripcion_corta', models.CharField(max_length=255)),
                ('descripcion_completa', models.TextField(blank=True, null=True)),
                ('icono', models.CharField(blank=True, help_text='Nombre del icono libreria frontend', max_length=100, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='servicios/')),
                ('destacado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['orden', 'titulo'],
            },
        ),
    ]
