# Generated by Django 6.0.4 on 2026-04-16 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=150, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('imagen', models.ImageField(upload_to='servicios/galeria/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Imagen de servicio',
                'verbose_name_plural': 'Imágenes de servicio',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
